// Database type definitions based on the Supabase schema
// This file will be automatically generated by Supabase CLI, but we're creating it manually for now

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          avatar_url: string | null
          role: 'user' | 'admin'
          status: 'active' | 'banned'
          must_change_password: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          status?: 'active' | 'banned'
          must_change_password?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          avatar_url?: string | null
          role?: 'user' | 'admin'
          status?: 'active' | 'banned'
          must_change_password?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      tags: {
        Row: {
          id: number
          name: string
          slug: string
          color: string
          created_at: string
        }
        Insert: {
          name: string
          slug: string
          color?: string
          created_at?: string
        }
        Update: {
          id?: number
          name?: string
          slug?: string
          color?: string
          created_at?: string
        }
      }
      prompts: {
        Row: {
          id: number
          title: string
          description: string | null
          content: string
          cover_image_url: string | null
          is_public: boolean
          author_id: string
          view_count: number
          copy_count?: number
          created_at: string
        }
        Insert: {
          title: string
          description?: string | null
          content: string
          cover_image_url?: string | null
          is_public?: boolean
          author_id: string
          view_count?: number
          copy_count?: number
          created_at?: string
        }
        Update: {
          id?: number
          title?: string
          description?: string | null
          content?: string
          cover_image_url?: string | null
          is_public?: boolean
          author_id?: string
          view_count?: number
          copy_count?: number
          created_at?: string
        }
      }
      prompt_tags: {
        Row: {
          prompt_id: number
          tag_id: number
        }
        Insert: {
          prompt_id: number
          tag_id: number
        }
        Update: {
          prompt_id?: number
          tag_id?: number
        }
      }
      copy_events: {
        Row: {
          id: number
          prompt_id: number
          user_id: string | null
          ip_address: string | null
          user_agent: string | null
          referrer: string | null
          created_at: string
        }
        Insert: {
          prompt_id: number
          user_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          prompt_id?: number
          user_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
        }
      }
      settings: {
        Row: {
          id: number
          settings: any // JSON object
          created_at: string
          updated_at: string
        }
        Insert: {
          id: number
          settings: any
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          settings?: any
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_view_count: {
        Args: {
          prompt_id: number
        }
        Returns: void
      }
      increment_copy_count: {
        Args: {
          prompt_id: number
        }
        Returns: void
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Type helpers for commonly used join operations
export type ProfileWithPrompts = Database['public']['Tables']['profiles']['Row'] & {
  prompts?: Database['public']['Tables']['prompts']['Row'][]
}

export type PromptWithTags = Database['public']['Tables']['prompts']['Row'] & {
  tags?: Database['public']['Tables']['tags']['Row'][]
  author?: Database['public']['Tables']['profiles']['Row']
}

export type PromptWithRelations = PromptWithTags & {
  _count?: {
    copies?: number
  }
}

// Helper types for forms and API responses
export interface CreatePromptInput {
  title: string
  description: string
  content: string
  cover_image_url?: string
  is_public: boolean
  tag_ids: number[]
}

export interface UpdatePromptInput {
  id: number
  title?: string
  description?: string
  content?: string
  cover_image_url?: string
  is_public?: boolean
  tag_ids?: number[]
}

export interface CreateTagInput {
  name: string
  slug: string
  color?: string
}

export interface UpdateUserInput {
  id: string
  username?: string
  avatar_url?: string
  role?: 'user' | 'admin'
  status?: 'active' | 'banned'
  must_change_password?: boolean
}

// Search and filter types
export interface SearchParams {
  query?: string
  tags?: string[]
  sort?: 'created_at' | 'title' | 'view_count'
  order?: 'asc' | 'desc'
  limit?: number
  offset?: number
}

export interface SearchResult {
  prompts: PromptWithRelations[]
  total: number
  hasMore: boolean
}

// Authentication types
export interface AuthUser {
  id: string
  email: string
  role: 'user' | 'admin'
  status: 'active' | 'banned'
  username?: string
  avatar_url?: string
}

// API response types
export interface ApiResponse<T = any> {
  success: boolean
  data?: T
  error?: string
  message?: string
}

// Copy tracking types
export interface CopyEvent {
  prompt_id: number
  user_id?: string
  ip_address?: string
  user_agent?: string
  created_at: string
}

// Settings types
export interface AdminSettings {
  copy_success_message: string
  site_name: string
  site_description: string
  allow_public_submissions: boolean
  require_approval: boolean
}