-- AI Prompt Library Database Schema (Simplified Setup)
-- Execute this in your Supabase SQL Editor

-- 1. 创建用户表
create table profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  status text default 'active' check (status in ('active', 'banned')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. 创建标签表
create table tags (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  color text default 'blue',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. 创建提示词表
create table prompts (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  content text not null,
  cover_image_url text,
  is_public boolean default true,
  author_id uuid references profiles(id),
  view_count bigint default 0,
  copy_count bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. 创建关联表
create table prompt_tags (
  prompt_id bigint references prompts(id) on delete cascade,
  tag_id bigint references tags(id) on delete cascade,
  primary key (prompt_id, tag_id)
);

-- 5. 创建复制事件表
create table copy_events (
  id bigint generated by default as identity primary key,
  prompt_id bigint references prompts(id) on delete cascade,
  user_id uuid references profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. 创建设置表
create table settings (
  id bigint generated by default as identity primary key,
  settings jsonb not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique (id)
);

-- 创建索引
create index on prompts (created_at desc);
create index on prompts (is_public, created_at desc);

-- 7. 创建管理员用户函数
create or replace function create_admin_user(email text, password text, username text)
returns void as $$
declare
  user_id uuid;
begin
  -- 创建用户
  insert into auth.users (email, password, email_confirmed_at)
  values (email, password, now())
  returning id into user_id;

  -- 创建管理员配置文件
  insert into profiles (id, username, role)
  values (user_id, username, 'admin');
end;
$$ language plpgsql security definer;

-- 8. 启用RLS
alter table profiles enable row level security;
alter table tags enable row level security;
alter table prompts enable row level security;
alter table prompt_tags enable row level security;
alter table copy_events enable row level security;
alter table settings enable row level security;

-- 9. 基本RLS策略
create policy "Public prompts are viewable by everyone" on prompts for select using (is_public = true);
create policy "Users can view own prompts" on prompts for select using (auth.uid() = author_id);
create policy "Authenticated users can create prompts" on prompts for insert with check (auth.uid() = author_id);
create policy "Users can update own prompts" on prompts for update using (auth.uid() = author_id);
create policy "Admins can manage all prompts" on prompts for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

create policy "Tags are viewable by everyone" on tags for select using (true);
create policy "Admins can manage tags" on tags for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

create policy "Anyone can create copy events" on copy_events for insert with check (true);
create policy "Users can view own copy events" on copy_events for select using (auth.uid() = user_id);

-- 10. 插入初始数据
insert into settings (id, settings) values (1, '{
  "copy_success_message": "✅ 复制成功！关注公众号回复[Coze]获取自动化版",
  "site_name": "PromptLib",
  "site_description": "发现高质量 AI 提示词"
}') on conflict (id) do nothing;

insert into tags (name, slug, color) values
  ('写作', 'writing', 'blue'),
  ('编程', 'programming', 'green'),
  ('Coze', 'coze', 'purple'),
  ('Midjourney', 'midjourney', 'red'),
  ('ChatGPT', 'chatgpt', 'orange'),
  ('Claude', 'claude', 'yellow'),
  ('自动化', 'automation', 'pink')
on conflict (slug) do nothing;

-- 完成提示
-- 执行完成后，在下面创建管理员账户