-- AI Prompt Library Database Schema
-- Execute this SQL in your Supabase SQL Editor

-- 1. 用户表 (增强版)
create table profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  status text default 'active' check (status in ('active', 'banned')),
  must_change_password boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. 标签表
create table tags (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  color text default 'blue',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. 提示词表 (增加封面图和复制计数)
create table prompts (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  content text not null, -- Markdown
  cover_image_url text,
  is_public boolean default true,
  author_id uuid references profiles(id),
  view_count bigint default 0,
  copy_count bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. 关联表
create table prompt_tags (
  prompt_id bigint references prompts(id) on delete cascade,
  tag_id bigint references tags(id) on delete cascade,
  primary key (prompt_id, tag_id)
);

-- 5. 复制事件追踪表
create table copy_events (
  id bigint generated by default as identity primary key,
  prompt_id bigint references prompts(id) on delete cascade,
  user_id uuid references profiles(id) on delete set null,
  ip_address text,
  user_agent text,
  referrer text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. 系统设置表
create table settings (
  id bigint generated by default as identity primary key,
  settings jsonb not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique (id)
);

-- 创建索引以优化查询性能
create index on prompts (created_at desc);
create index on prompts (view_count desc);
create index on prompts (copy_count desc);
create index on prompts (is_public, created_at desc);
create index on profiles (role);
create index on profiles (status);
create index on copy_events (prompt_id, created_at desc);
create index on copy_events (user_id, created_at desc);

-- 7. 函数：增加浏览量
create or replace function increment_view_count(prompt_id_param bigint)
returns void as $$
begin
  update prompts
  set view_count = view_count + 1
  where id = prompt_id_param;
end;
$$ language plpgsql;

-- 8. 函数：增加复制次数
create or replace function increment_copy_count(prompt_id_param bigint)
returns void as $$
begin
  update prompts
  set copy_count = coalesce(copy_count, 0) + 1
  where id = prompt_id_param;
end;
$$ language plpgsql;

-- 9. 函数：自动更新 updated_at 时间戳
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- 10. 触发器：自动更新设置表的 updated_at
create trigger update_settings_updated_at
  before update on settings
  for each row
  execute function update_updated_at_column();

-- 11. RLS (Row Level Security) 策略
alter table profiles enable row level security;
alter table tags enable row level security;
alter table prompts enable row level security;
alter table prompt_tags enable row level security;
alter table copy_events enable row level security;
alter table settings enable row level security;

-- Profiles 表策略
-- 用户可以查看自己的资料
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);

-- 用户可以更新自己的资料（某些字段）
create policy "Users can update own profile" on profiles for update using (auth.uid() = id) with check (
  auth.uid() = id and
  role = 'user' -- 防止普通用户将自己提升为管理员
);

-- 管理员可以查看所有资料
create policy "Admins can view all profiles" on profiles for select using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- 管理员可以更新所有资料
create policy "Admins can update all profiles" on profiles for update using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- Prompts 表策略
-- 所有人可以查看公开的提示词
create policy "Public prompts are viewable by everyone" on prompts for select using (is_public = true);

-- 认证用户可以查看自己的所有提示词
create policy "Users can view own prompts" on prompts for select using (auth.uid() = author_id);

-- 用户可以创建提示词
create policy "Authenticated users can create prompts" on prompts for insert with check (auth.uid() = author_id);

-- 用户可以更新自己的提示词
create policy "Users can update own prompts" on prompts for update using (auth.uid() = author_id);

-- 用户可以删除自己的提示词
create policy "Users can delete own prompts" on prompts for delete using (auth.uid() = author_id);

-- 管理员可以查看和操作所有提示词
create policy "Admins can manage all prompts" on prompts for all using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- Tags 表策略
-- 所有人可以查看标签
create policy "Tags are viewable by everyone" on tags for select using (true);

-- 管理员可以管理标签
create policy "Admins can manage tags" on tags for all using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- Prompt_tags 表策略
-- 根据关联的提示词可见性来决定
create policy "Prompt tags inherit prompt visibility" on prompt_tags for select using (
  exists (
    select 1 from prompts
    where prompts.id = prompt_tags.prompt_id and (
      prompts.is_public = true or prompts.author_id = auth.uid()
    )
  )
);

-- 用户可以为自己的提示词添加标签
create policy "Users can manage tags for own prompts" on prompt_tags for all using (
  exists (
    select 1 from prompts
    where prompts.id = prompt_tags.prompt_id and prompts.author_id = auth.uid()
  )
);

-- 管理员可以管理所有提示词标签
create policy "Admins can manage all prompt tags" on prompt_tags for all using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- Copy_events 表策略
-- 用户可以查看自己的复制事件
create policy "Users can view own copy events" on copy_events for select using (auth.uid() = user_id);

-- 所有人（包括匿名用户）可以创建复制事件
create policy "Anyone can create copy events" on copy_events for insert with check (true);

-- 管理员可以查看所有复制事件
create policy "Admins can view all copy events" on copy_events for select using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- Settings 表策略
-- 管理员可以管理设置
create policy "Admins can manage settings" on settings for all using (
  exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  )
);

-- 12. 插入初始数据
-- 插入默认设置
insert into settings (id, settings) values (1, '{
  "copy_success_message": "✅ 复制成功！关注公众号回复[Coze]获取自动化版",
  "site_name": "PromptLib",
  "site_description": "发现高质量 AI 提示词",
  "allow_public_submissions": false,
  "require_approval": false
}') on conflict (id) do nothing;

-- 插入一些初始标签
insert into tags (name, slug, color) values
  ('写作', 'writing', 'blue'),
  ('编程', 'programming', 'green'),
  ('Coze', 'coze', 'purple'),
  ('Midjourney', 'midjourney', 'red'),
  ('ChatGPT', 'chatgpt', 'orange'),
  ('Claude', 'claude', 'yellow'),
  ('自动化', 'automation', 'pink')
on conflict (slug) do nothing;

-- 13. 创建一些有用的视图
-- 热门提示词视图
create view popular_prompts as
select
  p.*,
  a.username as author_name,
  a.avatar_url as author_avatar,
  coalesce(array_agg(t.name) filter (where t.name is not null), '{}') as tags
from prompts p
left join profiles a on p.author_id = a.id
left join prompt_tags pt on p.id = pt.prompt_id
left join tags t on pt.tag_id = t.id
where p.is_public = true
group by p.id, a.username, a.avatar_url
order by p.copy_count desc, p.view_count desc;

-- 提示词统计视图
create view prompt_stats as
select
  count(*) as total_prompts,
  count(*) filter (where is_public = true) as public_prompts,
  sum(view_count) as total_views,
  sum(copy_count) as total_copies,
  count(*) filter (where created_at >= now() - interval '7 days') as new_this_week
from prompts;

-- 用户统计视图
create view user_stats as
select
  count(*) as total_users,
  count(*) filter (where status = 'active') as active_users,
  count(*) filter (where role = 'admin') as admin_users,
  count(*) filter (where status = 'banned') as banned_users
from profiles;

-- 完成执行
-- 请确保在执行此 SQL 后：
-- 1. 创建第一个管理员用户（使用 createAdminUser 函数或直接在 Supabase 中创建）
-- 2. 配置 OAuth 提供商（GitHub、Google）
-- 3. 设置环境变量
-- 4. 测试 RLS 策略是否正常工作